version: "3.7"
services:
  db:
    image: mysql:5.7
    command: --lower_case_table_names=1 --sql_mode="" --character-set-client-handshake=FALSE --character-set-server="utf8mb4" --collation-server="utf8mb4_unicode_ci" --max_allowed_packet=500M
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
      - TZ=UTC
    # volumes: host_path:container_path
    volumes:
      - "./dataBaseStuff/Data:/var/lib/mysql"
      - "./dockerStuff/mysqlInitSql:/docker-entrypoint-initdb.d"

networks:
  atom:
    driver: bridge
